const LOGIN = 'LOGIN';
const SIGN_UP_NAME = 'SIGN_UP_NAME'
const SIGN_UP_BENEFITS = 'SIGN_UP_BENEFITS'
const SIGN_UP_PHONENUMBER = 'SIGN_UP_PHONENUMBER'
const SIGN_UP_CREDIT_CARD = 'SIGN_UP_CREDIT_CARD'
const SIGN_UP_PASSWORD = 'SIGN_UP_PASSWORD'
const MAIN = 'MAIN'
const PUBLIC_TRANSPORT = 'PUBLIC_TRANSPORT'
const TRAVEL_ROUTE = 'TRAVEL_ROUTE'
const BUY_TICKET = 'BUY_TICKET'
const TICKET = 'TICKET'
const SELECTED_TRANSPORT = 'SELECTED_TRANSPORT'
const ALL = 'ALL'

export {
    LOGIN,
    SIGN_UP_NAME,
    SIGN_UP_BENEFITS,
    SIGN_UP_PHONENUMBER,
    SIGN_UP_CREDIT_CARD,
    MAIN,
    PUBLIC_TRANSPORT,
    TRAVEL_ROUTE,
    BUY_TICKET,
    TICKET,
    SELECTED_TRANSPORT,
    ALL,
    SIGN_UP_PASSWORD
}